
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# upload libraries to upload and process data

library(tidyverse)
library(infer)

```



```{r q5_rpub, echo = FALSE}

# made a tibble which had an id col and using rep a grade col.

pop <- tibble(id = c(1:6120),
              grade = c(rep("freshman", 1800),
                        rep("sophomore", 1450),
                        rep("junior", 1570),
                        rep("senior", 1300)
                        )
              )


# creates a named list sizes which displays what size a sample was when
# proportion was calculated to use with map_df

samp_size = c(25,50,100,500)
sizes <- set_names(samp_size, nm = samp_size)

set.seed(02139)

# use map_df to make a table which samples from pop 5000 times per each size in
# sizes, and labels which size number each rep slice came from. Then, group_by
# size and rep number (w/o grouping many samples are not disjoint) and find the
# proportion of freshman per every rep. calculate prop_frosh with as.numeric
# size since named list sizes had size vales as chr

university <- map_df(sizes,
                     ~ rep_sample_n(pop,
                                    size = .x,
                                    reps = 5000),
                     .id = "size"
                     )  %>% 
  group_by(size, replicate) %>% 
  summarize(frosh = sum(grade == "freshman")) %>%    
  mutate(prop_frosh = frosh/as.numeric(size))


# use ggplot geom_density to graph distribution of percentage of freshman count
# change based on size which was sampled. used factor to relevel size so that
# legend values appear in the value we desire. set ggplot to frosh_plot so can
# call on it in ggsave()

university$size <- factor(university$size, levels = c("25", "50", "100", "500"))
                    
frosh_plot <- ggplot(university, aes(x = prop_frosh, fill = size)) +
  geom_density(alpha = 0.25) +
  theme_classic() +
  labs(title = "Distribution of Percentage of Freshmen",
       subtitle = "Average sampled percentage gets closer to true percentage as sample size increases",
       x = "Proportion of freshmen",
       y = "Count")

frosh_plot

ggsave("graphics", frosh_plot)
  
```
  
  
  